- src/UnicodePlots.jl
Shave a bit off of startup time.  :)
> Enable Precompilation

- src/spy.jl
- test/tst_plots.jl
An implementation of `findnz` is really all that is required for an `AbstractArray` implementation.
> Relax type for spy plots

- src/UnicodePlots.jl
- src/interface/lineplot.jl
Sorry for the previous noise, you've done quite a bit of work since last I pulled this repo.
> support for time series using Base.Dates added closes #36

- src/common.jl
- src/plot.jl
- test/tst_plots.jl
Fix for #51, tested it with random inputs for a while a worked like a charm.
> Fix InexactError() bug

- REQUIRE
- src/graphics/bargraphics.jl
These should accommodate @tkelman's comments to the METADATA PR.
> Better 0.6 fixes

- .travis.yml
- src/canvas.jl
- src/graphics/bargraphics.jl
- src/interface/barplot.jl
- src/interface/densityplot.jl
- src/interface/lineplot.jl
- src/interface/stairs.jl
- src/plot.jl
Fix #73 
The outputs in the test suite looked correct to me, but I appreciate if you can double check.
> Replace all occurrences of Vector by AbstractVector in plot commands

- .travis.yml
Travis _should_ now be happy across 0.7+ versions
> Update travis.yml to 0.7/1.0

- README.md
Added dots before plus for new broadcasting.  This is an amazing package!!! Thanks!
> Update readme.md density plot example

- Project.toml
- REQUIRE
- test/REQUIRE
Hi!
I am submitting a commit that adds `Project.toml` to the project.
Regarding the tests, against the latest version of Julia, there is a type inference error that I could not solve. Thus, I did not include the modifications to test against Julia 1.3 yet.
Closes #103
> Add Project.toml to the project

- Project.toml
It would be also great if a new version of the package could be registered if this gets merged. Thank you!
> allow latest version of StatsBase.jl

- src/common.jl
- test/tst_histogram.jl
> allow histogram edges to be integer

- src/canvas.jl
- src/interface/lineplot.jl
- test/tst_canvas.jl
- test/tst_lineplot.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/106.
> Replace !isnan with isfinite

- src/UnicodePlots.jl
- src/plot.jl
- test/tst_plot.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/28.
> Add basic `savefig` implementation

- src/canvas.jl
- src/common.jl
- src/interface/barplot.jl
- src/interface/boxplot.jl
- src/interface/heatmap.jl
- src/interface/lineplot.jl
- src/interface/spy.jl
https://github.com/JuliaPlots/UnicodePlots.jl/pull/156#discussion_r702418099.
> Rename `os` to `out_stream`

- README.md
- squeeze spaces in examples
- visual changes
> minor docs update

- README.md
- docs/generate_docs.jl
Following https://github.com/JuliaPlots/UnicodePlots.jl/pull/206.
> Fix broken url

- src/canvas.jl
- src/common.jl
- src/graphics.jl
- src/interface/boxplot.jl
- src/interface/lineplot.jl
- src/interface/spy.jl
- src/plot.jl
Split from https://github.com/JuliaPlots/UnicodePlots.jl/pull/202.
> make border_color a ref

- src/plot.jl
> Fix default projection when using explicit canvas

- README.md
- docs/generate_docs.jl
Rework documentation in collapsible sections.
> Rework documentation

- src/canvas.jl
- src/interface/barplot.jl
- src/interface/heatmap.jl
- src/interface/histogram.jl
After reading https://discourse.julialang.org/t/discussion-on-why-i-no-longer-recommend-julia-by-yuri-vishnevsky/81151/67 :wink:
> code quality

- .github/workflows/ci.yml
- .github/workflows/format-check.yml
> use `action@latest` if possible

- Project.toml
- src/graphics/bargraphics.jl
- test/runtests.jl
- test/tst_quality.jl
- `FreeTypeAbstraction` compat;
- test using `Aqua` (quality check);
- fix ambiguity detected by `Aqua`.
> `FreeTypeAbstraction` compat - add `Aqua` test / fix ambiguity

- .github/workflows/format-check.yml
- .github/workflows/invalidations.yml
https://discourse.julialang.org/t/potential-performance-regressions-in-julia-1-8-for-special-un-precompiled-type-dispatches-and-how-to-fix-them/86359/11
Closes https://github.com/JuliaPlots/UnicodePlots.jl/issues/287 (`UnicodePlots` dependencies related, nothing we can do in this repo).
> add `invalidations.yml` check

- src/freetype.jl
On `1.8.2`:
```julia
julia> using UnicodePlots
julia> pl = lineplot(1:2)
julia> @time savefig(pl, tempname() * ".png")
julia> @time savefig(pl, tempname() * ".png")
0.194326 seconds (62.12 k allocations: 23.667 MiB)
```
> increase coverage - freetype simplifications

- src/common.jl
- test/tst_common.jl
- test/tst_issues.jl
Better fix for https://github.com/JuliaPlots/UnicodePlots.jl/issues/297.
Only warn and don't error.
> better fix on big amplitude

- src/common.jl
- src/freetype.jl
- src/graphics/imagegraphics.jl
- src/interface/imageplot.jl
- src/show.jl
Xref https://github.com/JuliaCI/Coverage.jl/issues/326.
> use `COV_EXCL_LINE` instead of `COV_EXCL_START` - `COV_EXCL_STOP`

- src/common.jl
- src/interface/isosurface.jl
- src/interface/surfaceplot.jl
- src/plot.jl
- src/volume.jl
Small minor simplifications.
Enhance docstrings.
> simplifications - swap transform order

- src/freetype.jl
- src/show.jl
- test/tst_freetype.jl
- test/tst_io.jl
> Add warning on failing font, and refuse to create image

- src/show.jl
> do not error on failing `png_image`

- README.md
- docs/gen_docs.jl
- src/plot.jl
- src/show.jl
> make `margin` and `padding` mutable

- src/common.jl
> ceil_neg_log10(x) for non-finite x

- Project.toml
- ext/IntervalSetsExt.jl
- ext/UnitfulExt.jl
- src/UnicodePlots.jl
- src/common.jl
- src/interface/lineplot.jl
- test/runtests.jl
- test/tst_lineplot.jl
```julia
julia> using UnicodePlots, IntervalSets
julia> lineplot(identity, 0..2)
```
> support `IntervalSets` through weak deps

- ext/UnitfulExt.jl
- src/common.jl
- src/plot.jl
- test/tst_issues.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/356.
> Fix Unitful bugs

- src/interface/lineplot.jl
> update lineplot docs

- .github/workflows/ci.yml
- README.md
- docs/gen_docs.jl
- fix a few typos;
- add upcoming `1.10` rc to CI;
- relax nightly for failures.
> fix a few typos

- README.md
Re. https://github.com/JuliaPlots/UnicodePlots.jl/issues/365#issuecomment-1869088224
> Add note about setting limits

- README.md
- docs/gen_docs.jl
Continuation of https://github.com/JuliaPlots/UnicodePlots.jl/pull/370.
> re-generate README.md

- .github/workflows/ci.yml
- .github/workflows/format-check.yml
- .github/workflows/invalidations.yml
Per following [PSA](https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857?u=t-bltg).
> update ci yml (codecov)

- src/common.jl
- src/interface/lineplot.jl
- src/plot.jl
- src/show.jl
- src/volume.jl
- test/runtests.jl
- test/tst_issues.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/404.
> fix `width=:auto` issue

- docs/Project.toml
- docs/src/api.md
- docs/src/dev.md
- docs/src/manual.md
> enrich dows

- .pre-commit-config.yaml
Add [pre-commit](https://pre-commit.com) hooks, so that the following checks are done:
```bash
$ git add .
$ git commit -a -m <msg>
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
check runic formatting...................................................Passed
[<branch> 57db8f9a] <msg>
xx files changed, xx insertions(+), xx deletions(-)
```
This enhances code quality.
> add `pre-commit` hook
