- src/plot.jl
When printing to something other than ``STDOUT`` the missing ``io`` argument was messing up the output.
(Awesome package btw!)
> Add missing 'io' argument.

- REQUIRE
- src/UnicodePlots.jl
- src/barplot.jl
- src/braillecanvas.jl
- src/common.jl
- src/densitycanvas.jl
- src/densityplot.jl
- src/histogram.jl
- src/plot.jl
- src/scatterplot.jl
- src/spy.jl
- test/runtests.jl
- test/tst_plots.jl
Now requires Compat.jl to maintain compatibility with Julia 0.3
> Fix deprecation warnings on Julia 0.4

- src/histogram.jl
This will automatically select the number of bins based on Sturges' rule.
This rule is used in the `Base.hist` function.
> select the number of histogram bins automatically

- src/interface/histogram.jl
- test/tst_plots.jl
When plotting a histogram using some large numbers I noticed that the range of the bins was incorrect:
```julia
julia> histogram(rand(800) * 10000 - 115000, title="Histogram")
Histogram
┌────────────────────────────────────────┐ 
(-120000.0,-120000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 64             │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 84      │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75         │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 85      │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 77         │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 87     │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 69            │ 
(-110000.0,-110000.0] │▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 80        │ 
(-110000.0,-110000.0] …
```
> Fix histogram range display for large values

- src/graphics/asciicanvas.jl
- src/interface/spy.jl
Fixed deprecated functions,
- WARNING: `x $ y` is deprecated.  use `xor(x, y)` or `x ⊻ y` instead.
- WARNING: tty_size is deprecated. use `displaysize(io)` as a replacement
thanks.
> Fix deprecated $, tty_size

- src/common.jl
- test/tst_plots.jl
`float_round_log10` now returns same float type it was given.
This (at the very least) fixes calls to `histogram(...)` with arrays of `Float32`: previously, calling `histogram` with an array of `Float32` would crash with:
```jl
ERROR: LoadError: TypeError: float_round_log10: in typeassert, expected Float64, got Float32
```
> Fixes calls to `histogram(...)` with arrays of `Float32`

- src/UnicodePlots.jl
- src/graphics/boxgraphics.jl
- src/interface/boxplot.jl
- test/tst_plots.jl
Addresses #13 - currently only supports horizontal plots (my preference), but vertical box plot support could be added down the line.
It is a known limitation that if the scale is set too high, only some of the features of the box plot will not be drawn. This is not considered important since a text-based display can only draw so much detail in any case.
Example of a box plot with multiple data series:
```
Multi-series
┌────────────────────────────────────────┐ 
│        │ ┌──┬──┐  │                    │ 
│        ├─┤  │  ├──┤                    │ 
│        │ └──┴──┘  │                    │ 
│          │    ┌────┬────┐    │         │ 
│          ├────┤    │    ├────┤         │ 
│          │    └────┴────┘    │         │ 
│  │       ┌──┬──┐                   │   │ 
One more │  ├───────┤  │ …
```
> Add box-and-whisker plots

- src/canvas.jl
- src/interface/lineplot.jl
Added a couple of lines which allows lineplot to work with vectors containing NaN values, e.g.
> added support for vectors containing NaN in lineplot

- src/interface/heatmap.jl
Also fixes some docs for default values given `[0,0] == (0.,0.)` is `false`
> `heatmap`: add `zlim` kwarg for setting color range

- src/canvas/densitycanvas.jl
```julia
using UnicodePlots
function tile(α)
io = IOBuffer()
color = round(Int64, 255α)
if α < 0
code = "\x1b[38;2;$(-color);0;0m"
else
code = "\x1b[38;2;0;0;$(color)m"
end
endc = "\x1b[0m"
print(IOContext(io, :color => true), code, "█", endc)
return String(take!(io))
end
main() = begin
UnicodePlots.den_signs[] = [tile(i) for i ∈ range(-1, 1, length=40)]
show(densityplot(randn(1000), randn(1000)))
return
end
main()
```
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/77.
> Allow den_signs override

- README.md
- src/common.jl
- src/plot.jl
When using `xlabel` and `ylabel`, use `label!` to save up space (especially width), when new keyword `compact=true` (default).
This is mostly useful when `min/max` strings are long (e.g. when using a scale), in conjunction with a long `ylabel`.
The height save is marginal (one line).
Example:
```julia
using UnicodePlots
x = y = collect(9:101);
lineplot(x, y, xlabel="x", ylabel="a very, very long label", xscale=:log10, yscale=:log10)
```
**before**
**after**
One can always restore the previous behavior by toggling the `compact=false` keyword:
```julia
lineplot(x, y, xlabel="x", ylabel="a very, very long label", xscale=:log10, yscale=:log10, compact=false)
```
> Save space by moving labels

- src/common.jl
- test/runtests.jl
- test/tst_common.jl
- Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/134.
```bash
$ julia --color=yes -e 'using Pkg; pkg"test UnicodePlots"'
$ julia --color=no  -e 'using Pkg; pkg"test UnicodePlots"'
```
, until https://github.com/KristofferC/Crayons.jl/issues/47 is fixed.
- Code cleanup, use `NamedTuple` instead of `Dict` (faster):
**before**
```julia
julia> using UnicodePlots
julia> @time lineplot([0, 4, 8], [10, 1, 10], color = :blue, name = "other line")
1.096257 seconds (858.07 k allocations: 52.733 MiB, 4.19% gc time, 99.74% compilation time)
julia> @time lineplot([0, 4, 8], [10, 1, 10], color = :blue, name = "other line")
0.000232 seconds (1.09 k allocations: 29.000 KiB)
```
**after**
```julia
julia> using UnicodePlots
@time lineplot([0, 4, 8], [10, 1, 10], color = :blue, name = "other …
```
> Force color in tests for `PkgEval`

- src/interface/lineplot.jl
Implement `:tail`, `:head` or `:both` color markers on a line to mimic an arrow.
See example at https://github.com/JuliaPlots/Plots.jl/pull/4031.
> Tail / head on `lineplot`

- src/plot.jl
- test/tst_issues.jl
- test/tst_plot.jl
Slight followup of https://github.com/JuliaPlots/UnicodePlots.jl/pull/205, where we now use `width = 0` to make the canvas disappear (`visible` = false).
We need this to make blank plots disappear in `Plots.jl` layouts.
> Ease making canvas invisible

- README.md
- docs/generate_docs.jl
When switching images from `1.x` to `2.x` (somewhere around https://github.com/JuliaPlots/UnicodePlots.jl/pull/177), I accidentally changed `rand(...)` to `randn(...)` calls. Restore that.
**old**
**new**
**1.x**
> Fix canvas example (`randn` -> `rand`), docs

- .gitignore
- src/interface/isosurface.jl
- src/interface/surfaceplot.jl
- src/volume.jl
- test/tst_volume.jl
When doing 3D, transforming points is quite costly in terms of allocations. Maybe I'll find time to rewrite the whole transform thing by preallocating (which will certainly be a tradeoff for readability), but for now small improvements like the following are unavoidable.
**master**
```julia
julia> using BenchmarkTools, UnicodePlots
julia> @btime surfaceplot(-8:.5:8, -8:.5:8, (x, y) -> 15sinc(√(x^2 + y^2) / π), lines=true);
32.321 ms (266809 allocations: 16.65 MiB)
```
**pr**
```julia
julia> using BenchmarkTools, UnicodePlots
julia> @btime surfaceplot(-8:.5:8, -8:.5:8, (x, y) -> 15sinc(√(x^2 + y^2) / π), lines=true);
27.441 ms (233254 allocations: 11.25 MiB)
```
> Reduce allocs

- Project.toml
- src/UnicodePlots.jl
- src/canvas.jl
- src/canvas/braillecanvas.jl
- src/canvas/densitycanvas.jl
- src/canvas/heatmapcanvas.jl
- src/canvas/lookupcanvas.jl
- src/common.jl
- src/graphics.jl
- src/graphics/bargraphics.jl
- src/graphics/boxgraphics.jl
- src/plot.jl
- test/runtests.jl
- test/tst_deprecated_warns.jl
- test/tst_plot.jl
Allow saving plot as `png` file using `FreeTypeAbstraction`.
Needs https://github.com/JuliaPlots/UnicodePlots.jl/pull/238 (true colors, `RGB`).
Needs https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/69.
**transparent**
**non-transparent**
> Save `Plot` as `png`

- .gitignore
- .vscode/settings.json
I didn't open the Julia auto formatter for my vscode because many old projects use random formats. But it's a good idea to provide a workspace-specific configuration so that everyone who devves UnicodePlots gets format on.
I also add `.vscode` into gitignore, so every changes to `.vscode` needs a force git add, e.g., `git add .vscode/settings.json -f`
> force auto formatting for vscode

- Project.toml
- src/UnicodePlots.jl
Unlike the filename version, the stream version has to manually create `DataFormat`; here FileIO is no longer a black-box and thus introduces world-age issues.
Let's roll back to still eagerly load it.
Since this is a bug fix, I'll merge and tag a release once the test passes.
> eagerly load FileIO

- README.md
- docs/generate_docs.jl
- src/UnicodePlots.jl
- src/canvas.jl
- src/canvas/asciicanvas.jl
- src/canvas/blockcanvas.jl
- src/canvas/braillecanvas.jl
- src/canvas/densitycanvas.jl
- src/canvas/dotcanvas.jl
- src/canvas/heatmapcanvas.jl
- src/canvas/lookupcanvas.jl
- src/colormaps.jl
- src/common.jl
- src/description.jl
- src/graphics.jl
- src/graphics/bargraphics.jl
- src/graphics/boxgraphics.jl
- src/interface/barplot.jl
- src/interface/boxplot.jl
- src/interface/heatmap.jl
- src/interface/histogram.jl
- src/interface/isosurface.jl
- src/interface/lineplot.jl
- src/interface/scatterplot.jl
- src/interface/spy.jl
- src/interface/surfaceplot.jl
- src/plot.jl
- src/volume.jl
- test/tst_common.jl
- fix embarrassing swap of width and height in `out_stream_size`;
- make `default_size!` return `(h, w)`, and export the symbol;
- enforce uppercasing `const` globals (convention, readability);
- code style modernization (mostly unicode syms).
Should be backward compatible, bug fix version.
Nightly failure is unrelated (https://github.com/JuliaStats/StatsBase.jl/pull/792 merged but not yet released in `StatsBase`), following https://github.com/JuliaLang/julia/pull/45576.
> Fix `width` - `height` order - style consistency

- Project.toml
- src/common.jl
- src/interface/barplot.jl
- test/runtests.jl
- test/tst_common.jl
Access `ColorSchemes` colormap through `ColorSchemes.colorschemes`'s Dict and not by const Symbol.
Allows using a custom registered cmap.
Added coverage test.
> fix custom registered scheme

- src/common.jl
- src/plot.jl
- test/tst_common.jl
- test/tst_issues.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/297.
```julia
julia> lineplot([-1.739368555288356e308, 1.291068489563134e307])
ERROR: DomainError with Invalid plotting range: (-1.739368555288356e308, 1.291068489563134e307):
Stacktrace:
[1] plotting_range_narrow
@ [...]/UnicodePlots.jl/src/common.jl:346 [inlined]
[2] extend_limits(vec::Vector{Float64}, lims::Tuple{Int64, Int64}, scale::typeof(identity))
@ UnicodePlots [...]/UnicodePlots.jl/src/common.jl:370
```
Don't error on large amplitude for weaker precision floats `lineplot([nextfloat(-Inf32), prevfloat(+Inf32)])`:
```julia
julia> lineplot([nextfloat(-Inf32), prevfloat(+Inf32)])
┌────────────────────────────────────────┐ 
Inf │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ 
│⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ …
```
> enhance error message for big amplitude

- README.md
- docs/gen_docs.jl
- Typo: "Know issues" → "Known issues"
- Normalize section heading capitalization to Sentence case
> README: Fix two section headings

- src/UnicodePlots.jl
Following https://discourse.julialang.org/t/psa-for-snoopprecompile-turning-off-extra-workload-for-specific-packages/92865.
See https://timholy.github.io/SnoopCompile.jl/dev/snoop_pc to reduce precompilation workload.
> remove `UP_PRECOMPILE` support

- src/common.jl
- src/interface/heatmap.jl
- src/volume.jl
- test/tst_common.jl
Bug introduced by https://github.com/JuliaPlots/UnicodePlots.jl/pull/327.
> fix `SVector` inferrability

- src/UnicodePlots.jl
Currently, the paths are resolved when the module is compiled which breaks relocatability.
> Use relative paths when including extensions in __init__

- test/tst_io.jl
Workaround for https://github.com/JuliaLang/julia/issues/53688.
> fix `1.11.0` test regression

- .github/workflows/ci.yml
- Project.toml
- ext/UnitfulExt.jl
- test/runtests.jl
- test/tst_io.jl
- test/tst_issues.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/383.
> fix unitful bug

- src/common.jl
- test/tst_issues.jl
Fix https://github.com/JuliaPlots/UnicodePlots.jl/issues/378.
> fix cornercase

- .github/workflows/ci.yml
- Project.toml
- ext/FreeTypeExt.jl
- ext/ImageInTerminalExt.jl
- ext/IntervalSetsExt.jl
- ext/TermExt.jl
- ext/UnitfulExt.jl
- src/UnicodePlots.jl
- src/common.jl
- test/tst_quality.jl
- drop `Requires` and use only extensions;
- support only LTS (per this [PSA](https://discourse.julialang.org/t/julia-v1-11-0-has-been-released-and-v1-10-is-now-lts/121064)), hence `julia >= 1.10`.
> adapt to new lts

- .github/workflows/ci.yml
- ext/FreeTypeExt.jl
- test/tst_freetype.jl
- test/tst_imageplot.jl
Adapt https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/87, all credits go to the PR author.
> make `FreeTypeExt` thread-safe

- src/UnicodePlots.jl
- src/common.jl
`__init__` must be called in `precompile_workload`.
Also, use `Base.get_have_truecolor` if possible.
> fix precompilation
